[local]
#127.0.0.1 ansible_connection=ssh ansible_port=22
127.0.0.1 ansible_connection=local
#10.244.185.183 ansible_connection=ssh ansible_port=22
#10.244.185.4 ansible_connection=ssh ansible_port=22
#10.244.185.246 ansible_connection=ssh ansible_port=22

[mobian]
#192.168.8.134 ansible_connection=ssh ansible_port=22

[local:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_become_timeout=30
ansible_become_method=sudo
target_user=kevin
target_group=kevin
target_home=/home/kevin
repos_root="{{ target_home }}/repos"
