---
- hosts: local
  tasks:

    - name: Creates nvim and autoload folder
      become: true
      become_user: root
      ansible.builtin.file:
        path: "{{ target_home }}/.config/nvim/autoload"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_group }}"

    - name: Symlink init.vim
      become: true
      become_user: root
      ansible.builtin.file:
        src: /repos/dotfiles/nvim/init.vim
        dest: "{{ target_home }}/.config/nvim/init.vim"
        state: link
        owner: "{{ target_user }}"
        group: "{{ target_group }}"

    - name: Symlink nvim plugin
      become: true
      become_user: root
      ansible.builtin.file:
        src: /repos/dotfiles/nvim/plugin/
        dest: "{{ target_home }}/.config/nvim/plugin"
        state: link
        owner: "{{ target_user }}"
        group: "{{ target_group }}"

    - name: Symlink vim-plug
      become: true
      become_user: root
      ansible.builtin.file:
        src: /repos/vim-plug/plug.vim
        dest: "{{ target_home }}/.config/nvim/autoload/plug.vim"
        state: link
        owner: "{{ target_user }}"
        group: "{{ target_group }}"

    - name: Symlink tmux
      become: true
      become_user: root
      ansible.builtin.file:
        src: /repos/dotfiles/tmux/
        dest: "{{ target_home }}/.config/tmux"
        state: link
        owner: "{{ target_user }}"
        group: "{{ target_group }}"

    - name: Symlink tmux conf
      become: true
      become_user: root
      ansible.builtin.file:
        src: "{{ target_home }}/.config/tmux/tmux.conf"
        dest: "{{ target_home }}/.tmux.conf"
        state: link
        owner: "{{ target_user }}"
        group: "{{ target_group }}"

    - name: Symlink tig
      become: true
      become_user: root
      ansible.builtin.file:
        src: /repos/dotfiles/tig/
        dest: "{{ target_home }}/.config/tig"
        state: link
        owner: "{{ target_user }}"
        group: "{{ target_group }}"

    - name: Symlink tigrc
      become: true
      become_user: root
      ansible.builtin.file:
        src: "{{ target_home }}/.config/tig/tigrc"
        dest: "{{ target_home }}/.tigrc"
        state: link
        owner: "{{ target_user }}"
        group: "{{ target_group }}"

    - name: Symlink gitconfig
      become: true
      become_user: root
      ansible.builtin.file:
        src: /repos/dotfiles/git/gitconfig
        dest: "{{ target_home }}/.gitconfig"
        state: link
        owner: "{{ target_user }}"
        group: "{{ target_group }}"

    - name: Creates i3 config
      become: true
      become_user: root
      ansible.builtin.file:
        path: "{{ target_home }}/.config/i3"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_group }}"

    - name: Symlink i3config
      become: true
      become_user: root
      ansible.builtin.file:
        src: /repos/dotfiles/i3/i3config
        dest: "{{ target_home }}/.config/i3/config"
        state: link
        owner: "{{ target_user }}"
        group: "{{ target_group }}"

    - name: Creates kitty config
      become: true
      become_user: root
      ansible.builtin.file:
        path: "{{ target_home }}/.config/kitty"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_group }}"

    - name: Symlink kitty
      become: true
      become_user: root
      ansible.builtin.file:
        src: /repos/dotfiles/kitty/kitty.conf
        dest: "{{ target_home }}/.config/kitty/kitty.conf"
        state: link
        owner: "{{ target_user }}"
        group: "{{ target_group }}"

    - name: Creates picom config
      become: true
      become_user: root
      ansible.builtin.file:
        path: "{{ target_home }}/.config/picom"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_group }}"

    - name: Symlink picom
      become: true
      become_user: root
      ansible.builtin.file:
        src: /repos/dotfiles/picom/picom.conf
        dest: "{{ target_home }}/.config/picom/picom.conf"
        state: link
        owner: "{{ target_user }}"
        group: "{{ target_group }}"

    - name: Creates ytfzf config
      become: true
      become_user: root
      ansible.builtin.file:
        path: "{{ target_home }}/.config/ytfzf"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_group }}"

    - name: Symlink ytfzf
      become: true
      become_user: root
      ansible.builtin.file:
        src: /repos/dotfiles/ytfzf/conf.sh
        dest: "{{ target_home }}/.config/ytfzf/conf.sh"
        state: link
        owner: "{{ target_user }}"
        group: "{{ target_group }}"

#    - name: Copy user.gitconfig
#      become: true
#      become_user: root
#      ansible.builtin.copy:
#        src: /repos/dotfiles/git/user.gitconfig
#        remote_src: true
#        dest: "{{ target_home }}/user.gitconfig"
#        owner: "{{ target_user }}"
#        group: "{{ target_group }}"
