---
- hosts: local
  tasks:
    - name: checkout dotfiles
      git:
        repo: 'https://github.com/kaevinlaw/dotfiles.git'
        dest: "{{ repos_dir }}/dotfiles"
        depth: 1
#    - name: checkout fzf
#      git:
#        repo: 'https://github.com/junegunn/fzf.git'
#        dest: "{{ repos_dir }}/fzf"
#        depth: 1
#    - name: checkout bat
#      git:
#        repo: 'https://github.com/sharkdp/bat.git'
#        dest: "{{ repos_dir }}/bat"
#        depth: 1
