---
- hosts: local
  become: true
  become_user: root
  tasks:
    - name: remap capslock to ctrl
      ansible.builtin.lineinfile:
        dest: /etc/default/keyboard
        regexp: '^XKBOPTIONS=""'
        line: 'XKBOPTIONS="ctrl:nocaps"'
