---
- hosts: local
  become: no
  tasks:
    - name: Ensure Node.js and npm are installed
      become: true
      ansible.builtin.apt:
        name:
          - nodejs
          - npm
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Install tree-sitter CLI globally via npm
      become: true
      community.general.npm:
        name: tree-sitter-cli
        global: true
        state: present

    - name: Install/update nvim plugins with lazy
      ansible.builtin.command: nvim --headless "+Lazy! sync" +qa
      changed_when: false
#    - name: Run CocInstall on coc-clangd
#      shell: nvim +'CocInstall -sync coc-clangd' +qall &> /dev/null < /dev/tty
#    - name: Run CocInstall on coc-cmake
#      shell: nvim +'CocInstall -sync coc-cmake' +qall &> /dev/null < /dev/tty
#    - name: Run CocInstall on coc-python
#      shell: nvim +'CocInstall -sync coc-python' +qall &> /dev/null < /dev/tty
