---
- hosts: local
  tasks:
    - name: install packages
      become: true
      become_user: root
      apt:
        state: present
        name:
          - moc
          - moc-ffmpeg-plugin
          - ffmpeg
          - mpv
          # for yt-fzf
          - jq
          - chafa
          - youtube-dl
          # - fzf already installe
