---
- hosts: local
  tasks:
    - name: install packages
      become: true
      become_user: root
      apt:
        state: fixed
        name:
          - xorg
          - xinit
          - xauth
          - i3
          - dmenu
          - i3status
          - feh
          - picom
          - conky
        update_cache: yes
        install_recommends: no
