---
- hosts: local
  tasks:
    - name: install packages
      become: true
      become_user: root
      apt:
        state: fixed
        name:
          - libasound2
          - libasound2-plugins
          - alsa-utils
          - alsa-oss
          - pulseaudio
          - pulseaudio-utils
        update_cache: yes
        install_recommends: no
