---
- hosts: local
  tasks:
    - name: install packages
      become: true
      become_user: root
      apt:
        state: present
        name:
            #nvim
          - neovim
          - ripgrep
          - fzf
          - bat

            #nodejs
          - nodejs
          - npm

            #python
          - python3
          - python3-pip
          - python3-distutils

            #dev related
          - clangd-11
          - build-essential
          - git
          - tig
          - repo

            #android
          - adb
          - fastboot

            #misc admin
          - tmux
          - curl
          - rsync
          - samba
          - ncdu
        update_cache: yes
        install_recommends: no
    - name: update alternatives for clangd
      become: true
      become_user: root
      alternatives:
          name: clangd
          link: /usr/bin/clangd
          path: /usr/lib/llvm-11/bin/clangd
          priority: 100
