---
- hosts: local
  tasks:
    - name: install packages
      become: true
      become_user: root
      apt:
        state: present
        name:
            #nvim
          - neovim
          - ripgrep
          - fzf
          - bat

            #nodejs
          - nodejs
          - npm

            #python
          - python3
          - python3-pip
          - python3-dev
          - python3-distutils

            #dev related
          - clangd-12
          - build-essential
          - git
          - tig
          - tree
          - repo
          - gdb
          - minicom
          - lnav
          - autoconf
          - automake
          - bison
          - libtool
          - libtool-bin
          - flex
          - texinfo
          - help2man
          - libncurses-dev

            #android
          - adb
          - fastboot
          - policycoreutils-python-utils

            #misc admin
          - tmux
          - curl
          - rsync
          - samba
          - ncdu
          - zip
          - unzip
          - p7zip

            #ripgrep-all
          - pandoc
          - poppler-utils
        update_cache: yes
        install_recommends: no
    - name: update alternatives for clangd
      become: true
      become_user: root
      alternatives:
          name: clangd
          link: /usr/bin/clangd
          path: /usr/lib/llvm-12/bin/clangd
          priority: 100
